# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab_container = QtGui.QTabWidget(self.centralwidget)
        self.tab_container.setGeometry(QtCore.QRect(10, 20, 781, 531))
        self.tab_container.setObjectName(_fromUtf8("tab_container"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.layoutWidget = QtGui.QWidget(self.tab_1)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 50, 361, 391))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.nombre_instancia_destino = QtGui.QLineEdit(self.layoutWidget)
        self.nombre_instancia_destino.setObjectName(_fromUtf8("nombre_instancia_destino"))
        self.gridLayout_2.addWidget(self.nombre_instancia_destino, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.nombre_basedatos_destino = QtGui.QLineEdit(self.layoutWidget)
        self.nombre_basedatos_destino.setObjectName(_fromUtf8("nombre_basedatos_destino"))
        self.gridLayout_2.addWidget(self.nombre_basedatos_destino, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.puerto_destino = QtGui.QLineEdit(self.layoutWidget)
        self.puerto_destino.setObjectName(_fromUtf8("puerto_destino"))
        self.gridLayout_2.addWidget(self.puerto_destino, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.nombre_usuario_destino = QtGui.QLineEdit(self.layoutWidget)
        self.nombre_usuario_destino.setObjectName(_fromUtf8("nombre_usuario_destino"))
        self.gridLayout_2.addWidget(self.nombre_usuario_destino, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.password_destino = QtGui.QLineEdit(self.layoutWidget)
        self.password_destino.setInputMask(_fromUtf8(""))
        self.password_destino.setEchoMode(QtGui.QLineEdit.Password)
        self.password_destino.setObjectName(_fromUtf8("password_destino"))
        self.gridLayout_2.addWidget(self.password_destino, 4, 1, 1, 1)
        self.boton_probar_destino = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_probar_destino.setFont(font)
        self.boton_probar_destino.setObjectName(_fromUtf8("boton_probar_destino"))
        self.gridLayout_2.addWidget(self.boton_probar_destino, 5, 1, 1, 1)
        self.boton_guardar_configuracion = QtGui.QPushButton(self.tab_1)
        self.boton_guardar_configuracion.setGeometry(QtCore.QRect(290, 460, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_guardar_configuracion.setFont(font)
        self.boton_guardar_configuracion.setObjectName(_fromUtf8("boton_guardar_configuracion"))
        self.label_11 = QtGui.QLabel(self.tab_1)
        self.label_11.setGeometry(QtCore.QRect(100, 10, 201, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_1)
        self.label_12.setGeometry(QtCore.QRect(490, 10, 221, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.widget = QtGui.QWidget(self.tab_1)
        self.widget.setGeometry(QtCore.QRect(10, 50, 361, 391))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nombre_instancia_origen = QtGui.QLineEdit(self.widget)
        self.nombre_instancia_origen.setAutoFillBackground(False)
        self.nombre_instancia_origen.setObjectName(_fromUtf8("nombre_instancia_origen"))
        self.gridLayout.addWidget(self.nombre_instancia_origen, 0, 1, 1, 1)
        self.nombre_basedatos_origen = QtGui.QLineEdit(self.widget)
        self.nombre_basedatos_origen.setObjectName(_fromUtf8("nombre_basedatos_origen"))
        self.gridLayout.addWidget(self.nombre_basedatos_origen, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.boton_probar_origen = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_probar_origen.setFont(font)
        self.boton_probar_origen.setObjectName(_fromUtf8("boton_probar_origen"))
        self.gridLayout.addWidget(self.boton_probar_origen, 5, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.nombre_usuario_origen = QtGui.QLineEdit(self.widget)
        self.nombre_usuario_origen.setObjectName(_fromUtf8("nombre_usuario_origen"))
        self.gridLayout.addWidget(self.nombre_usuario_origen, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.password_origen = QtGui.QLineEdit(self.widget)
        self.password_origen.setInputMask(_fromUtf8(""))
        self.password_origen.setEchoMode(QtGui.QLineEdit.Password)
        self.password_origen.setObjectName(_fromUtf8("password_origen"))
        self.gridLayout.addWidget(self.password_origen, 4, 1, 1, 1)
        self.puerto_origen = QtGui.QLineEdit(self.widget)
        self.puerto_origen.setObjectName(_fromUtf8("puerto_origen"))
        self.gridLayout.addWidget(self.puerto_origen, 2, 1, 1, 1)
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.nombre_basedatos_origen.raise_()
        self.label_2.raise_()
        self.password_origen.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.puerto_origen.raise_()
        self.boton_probar_origen.raise_()
        self.nombre_usuario_origen.raise_()
        self.nombre_instancia_origen.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        self.boton_guardar_configuracion.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.tab_container.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(230, 20, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.widget1 = QtGui.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(70, 70, 621, 341))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.boton_hacia_derecha = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_hacia_derecha.setFont(font)
        self.boton_hacia_derecha.setObjectName(_fromUtf8("boton_hacia_derecha"))
        self.gridLayout_3.addWidget(self.boton_hacia_derecha, 2, 1, 1, 2)
        self.label_13 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 2)
        self.boton_hacia_izquierda = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_hacia_izquierda.setFont(font)
        self.boton_hacia_izquierda.setObjectName(_fromUtf8("boton_hacia_izquierda"))
        self.gridLayout_3.addWidget(self.boton_hacia_izquierda, 3, 1, 2, 2)
        self.label_21 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.boton_cancelar = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_cancelar.setFont(font)
        self.boton_cancelar.setObjectName(_fromUtf8("boton_cancelar"))
        self.gridLayout_3.addWidget(self.boton_cancelar, 5, 2, 1, 2)
        self.label_20 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 3, 3, 1, 1)
        self.boton_guardar = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_guardar.setFont(font)
        self.boton_guardar.setObjectName(_fromUtf8("boton_guardar"))
        self.gridLayout_3.addWidget(self.boton_guardar, 5, 0, 1, 2)
        self.label_15 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 2, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 4, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 2, 1, 2)
        self.tab_container.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_container.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "Nombre Instancia", None))
        self.nombre_instancia_destino.setPlaceholderText(_translate("MainWindow", "nombre_instancia_destino", None))
        self.label_7.setText(_translate("MainWindow", "Nombre Base Datos", None))
        self.nombre_basedatos_destino.setPlaceholderText(_translate("MainWindow", "nombre_basedatos_destino", None))
        self.label_8.setText(_translate("MainWindow", "Puerto", None))
        self.puerto_destino.setPlaceholderText(_translate("MainWindow", "puerto_destino", None))
        self.label_9.setText(_translate("MainWindow", "Nombre Usuario", None))
        self.nombre_usuario_destino.setPlaceholderText(_translate("MainWindow", "nombre_usuario_destino", None))
        self.label_10.setText(_translate("MainWindow", "Password", None))
        self.password_destino.setPlaceholderText(_translate("MainWindow", "password_destino", None))
        self.boton_probar_destino.setText(_translate("MainWindow", "Probar ", None))
        self.boton_guardar_configuracion.setText(_translate("MainWindow", "Guardar", None))
        self.label_11.setText(_translate("MainWindow", "Base de Datos Origen", None))
        self.label_12.setText(_translate("MainWindow", "Base de Datos Destino", None))
        self.nombre_instancia_origen.setPlaceholderText(_translate("MainWindow", "nombre_instancia_origen", None))
        self.nombre_basedatos_origen.setPlaceholderText(_translate("MainWindow", "nombre_basedatos_origen", None))
        self.label_2.setText(_translate("MainWindow", "Nombre Base Datos", None))
        self.label_4.setText(_translate("MainWindow", "Nombre Usuario", None))
        self.boton_probar_origen.setText(_translate("MainWindow", "Probar ", None))
        self.label_5.setText(_translate("MainWindow", "Password", None))
        self.label_3.setText(_translate("MainWindow", "Puerto", None))
        self.nombre_usuario_origen.setPlaceholderText(_translate("MainWindow", "nombre_usuario_origen", None))
        self.label.setText(_translate("MainWindow", "Nombre Instancia", None))
        self.password_origen.setPlaceholderText(_translate("MainWindow", "password_origen", None))
        self.puerto_origen.setPlaceholderText(_translate("MainWindow", "puerto_origen", None))
        self.tab_container.setTabText(self.tab_container.indexOf(self.tab_1), _translate("MainWindow", "Configuracion de Base de Datos", None))
        self.label_23.setText(_translate("MainWindow", "Tablas BD Origen", None))
        self.boton_hacia_derecha.setText(_translate("MainWindow", ">>", None))
        self.label_13.setText(_translate("MainWindow", "Sin Replicar", None))
        self.boton_hacia_izquierda.setText(_translate("MainWindow", "<<", None))
        self.label_21.setText(_translate("MainWindow", "Item 4", None))
        self.label_17.setText(_translate("MainWindow", "Item 3", None))
        self.label_16.setText(_translate("MainWindow", "Item 2", None))
        self.boton_cancelar.setText(_translate("MainWindow", "Cancelar", None))
        self.label_20.setText(_translate("MainWindow", "Item 3", None))
        self.boton_guardar.setText(_translate("MainWindow", "Guardar", None))
        self.label_15.setText(_translate("MainWindow", "Item 1", None))
        self.label_18.setText(_translate("MainWindow", "Item 2", None))
        self.label_22.setText(_translate("MainWindow", "Item 4", None))
        self.label_19.setText(_translate("MainWindow", "Item 1", None))
        self.label_14.setText(_translate("MainWindow", "Replicando", None))
        self.tab_container.setTabText(self.tab_container.indexOf(self.tab_2), _translate("MainWindow", "Tablas BD Origen", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

